name: Scala CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: olafurpg/setup-scala@v10
      with:
        java-version: openjdk@1.11
    - name: Run tests
      run: |
            cd library
            sbt clean
            sbt "show fullResolvers"
            sbt -Dhttps.protocols=TLSv1,TLSv1.1,TLSv1.2 compile # bug jdk 11 https://stackoverflow.com/questions/52574050/javax-net-ssl-sslexception-no-psk-available-unable-to-resume
            sbt -J-Xmx4G "project test; testOnly org.openmole.spatialdata.scalatest.TestSuite"
