name: Scala CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: olafurpg/setup-scala@v10
      with:
        java-version: openjdk@1.11
    - name: Run tests
      run: |
            cd library
            export SBT_OPTS="-XX:+CMSClassUnloadingEnabled -XX:MaxPermSize=2G -Xmx4G"
            sbt clean
            sbt "show fullResolvers"
            sbt compile
            sbt "project test; testOnly org.openmole.spatialdata.scalatest.TestSuite"
